[package]
name = "tracing-rfc-5424"
version = "0.0.4"
edition = "2021"

[dependencies]
backtrace = "0.3.66"
bytes = "1.2.0"
chrono = "0.4.19"
hostname = "0.3.1"
local-ip-address = "0.4.5"
tracing = "0.1.35"
tracing-core = "0.1.28"
tracing-subscriber = "0.3.15"
