[package]
name = "rfc-5424-test"
version = "0.0.3"
edition = "2021"

[dependencies]
tracing = "0.1.36"
tracing-rfc-5424 = { version = "0.0.3", path = "../tracing-rfc-5424"}
tracing-subscriber = "0.3.15"
